Repository aeroteameindhoven/website, pull requests merged in 2023-05, with the labels that each got.

#20 Also remove previews when prs close
  .github/CODEOWNERS
  .github/workflows/pages-deploy.yml
  .github/workflows/preview-remove.yml
Labels: enhancement

#23 Fix bug left from pr preview
  .github/workflows/pages-deploy.yml
Labels: bug

#31 Fix up svgs to not interfere with each other and simplify their source
  .vscode/settings.json
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/layout/CompactNav.scss
  src/components/layout/CompactNav.tsx
  src/components/layout/FullSizeNav.scss
  src/components/layout/FullSizeNav.tsx
  src/components/styles/footer.module.scss
  src/images/hamburger.svg
  src/images/icons/email.svg
  src/images/icons/icons-instagram.svg
  src/images/icons/icons-linkedin.svg
  src/images/icons/icons-youtube.svg
  src/images/icons/linkedin.svg
  src/images/icons/phone.svg
  src/images/icons/press-kit.svg
  src/images/icons/presskit.svg
  src/images/sponsors/gls.svg
  src/images/sponsors/nxp.svg
  src/images/sponsors/tue.svg
  src/images/sponsors/zoomworks.svg
  src/svg/navLogo.svg
  src/svg/white-horizontal.svg
  src/svg/white-vertical.svg
Labels: bug

#29 Interest lunch
  src/components/Layout.tsx
  src/components/styles/home.scss
  src/components/styles/index.scss
  src/components/styles/layout.scss
  src/components/styles/partners.scss
  src/pages/index.tsx
Labels: enhancement

#30 Member update
  src/components/styles/team.scss
  src/components/team/TeamMemberCard.tsx
  src/data/22-23.csv
  src/hooks/useTeamMembers.tsx
  src/images/icons/linkedin-minimalist.svg
Labels: member update

#34 Use ackee for insights instead of google analytics
  .github/workflows/pages-deploy.yml
  gatsby-config.ts
  package.json
  yarn.lock
Labels: enhancement

#36 Enable detailed analytics
  gatsby-config.ts
Labels: enhancement
