Repository aeroteameindhoven/website, pull requests merged in 2024-04, with the labels that each got.

#73 Create Sponsors “gold/pcb-connect-b-v”
  content/images/sponsors/pcb-connect-png.png
  content/sponsors/gold/pcb-connect-b-v.md
Labels: decap-cms/pending_publish

#71 Create Sponsors “gold/volz-servos-gmbh-co-kg”
  content/images/sponsors/volz_servos_gmbh__co_kg_logo.svg
  content/sponsors/gold/volz-servos-gmbh-co-kg.md
Labels: decap-cms/pending_publish

#72 Create Sponsors “gold/st-microelectronics”
  content/images/sponsors/st_logo_2020_blue_v.svg.png
  content/sponsors/gold/st-microelectronics.md
Labels: decap-cms/pending_publish

#75 Create Sponsors “silver/workwear4all-b-v”
  content/images/sponsors/workwear4all-coupon-codes.png
  content/sponsors/silver/workwear4all-b-v.md
Labels: decap-cms/pending_publish

#74 Create Sponsors “gold/infinite-simulation-systems”
  content/images/sponsors/innoptus_infinite-1.svg
  content/sponsors/gold/infinite-simulation-systems.md
Labels: decap-cms/pending_publish

#84 Create Sponsors “silver/bomist”
  content/images/sponsors/bomist_logo.svg
  content/sponsors/silver/bomist.md
Labels: decap-cms/pending_publish

#81 Enable umami analytics
  .gitignore
  gatsby-config.ts
  package.json
  yarn.lock
Labels: enhancement

#82 Selfhost google fonts with fontsource
  gatsby-browser.ts
  package.json
  src/components/homePageSideSection.scss
  src/components/styles/layout.scss
  src/components/styles/notification.module.scss
  src/components/styles/scroll.scss
  yarn.lock
Labels: enhancement

#79 Remove markdown files that are just chillin
  src/sponsors/gold/HTC.md
  src/sponsors/gold/KPN.md
  src/sponsors/gold/Lab76.md
  src/sponsors/gold/Maxon.md
  src/sponsors/gold/NXP.md
  src/sponsors/gold/Wurth.md
  src/sponsors/platinum/GLS.md
  src/sponsors/platinum/TUe.md
  src/sponsors/silver/Easy Composites.md
  src/sponsors/silver/Zoomworks.md
Labels: bug
